#!/usr/bin/sh

lines=""
qshdir="$HOME/.q/"
qshfile="$qshdir""q"

ParseArgs () {
	while [ $# -gt 0 ]; do
		case "$1" in
			-d|--directory)
				qshdir="$(echo "$qshdir" | sed 's/\//\\\//g')"
				qshfile="$(echo "$qshfile" | sed 's/'"$qshdir"'//')"
				qshdir="$2/"
				qshfile="$qshdir""$qshfile"
				shift
			;;
			-f|--file)
				qshfile="$qshdir""$2"
				shift
			;;
			*)
				lines=$(echo "$lines
				$1" | sed 's/^\t\+//g')
			;;
		esac

		shift
	done

	lines="$(echo "$lines" | sed '1d')"
}

Init () {
	[ ! -f "$qshfile" ] && {
		[ ! -d "$qshfile" ] && {
			mkdir -p "$qshdir"
		}
		touch "$qshfile"
	}
}

ParseArgs "$@"
Init

if [ -z "$lines" ]; then
	if [ -s "$qshfile" ]; then
		sed q "$qshfile"
		sed -i '1d' "$qshfile"
	else
		echo "Nothing in your q!"
	fi
else
	echo "$lines" >> "$qshfile"
fi
