#!/usr/bin/sh

CheckFiles () {
	[ ! -f "$qshfile" ] && {
		[ ! -d "$qshfile" ] && {
			mkdir -p "$qshdir"
		}
		touch "$qshfile"
	}
}

Init () {
	lines=""
	qshdir="$HOME/.q/"
	qshfile="$qshdir""q"
}

ParseArgs () {
	while [ $# -gt 0 ]; do
		case "$1" in
			-d|--directory)
				qshdir="$(echo "$qshdir" | sed 's/\//\\\//g')"
				qshfile="$(echo "$qshfile" | sed 's/'"$qshdir"'//')"
				qshdir="$(echo "$2/" | sed 's/\/\/$/\//')"
				qshfile="$qshdir""$qshfile"
				shift
			;;
			-f|--file)
				qshfile="$qshdir""$2"
				shift
			;;
			*)
				lines=$(echo "$lines
				$1" | sed 's/^\t\+//g')
			;;
		esac

		shift
	done

	lines="$(echo "$lines" | sed '1d')"
}

Init
ParseArgs "$@"
CheckFiles

if [ -z "$lines" ]; then
	if [ -s "$qshfile" ]; then
		sed q "$qshfile"
		sed -i '1d' "$qshfile"
	else
		echo "Nothing in your q!"
	fi
else
	echo "$lines" >> "$qshfile"
fi
